### ISSUE TITLE
Please add a specific license

### ISSUE THREAD

**Issue by DuncanLithgow** [dnenov/pyChilizer#13]
I suggest GPL 2 or 3

**Comment by dnenov** [comment]
Good call, thanks @DuncanLithgow !

**Comment by DuncanLithgow** [comment]
Actually I just realized that your project depends on pyRevit which is GPLv3 so I'm pretty sure you're obliged to use the same license.

**Comment by dnenov** [comment]
Yup, that's what I've added. Thanks again!
