### ISSUE TITLE
Rooms data sheets

### ISSUE THREAD

**Issue by jmcouffin** [dnenov/pyChilizer#18]
>  Better suited here from @studioearl on the pyRevit repo https://github.com/eirannejad/pyRevit/issues/1710#issue-1551818019
> Cheers @dnenov @rastermadre 

Describe the bug

Sorry if this isn't the place to report this, I tried reaching out to archilizer, no response, if you don't handle this, can you connect me with the people/place that can?

Not sure if this is the right place to report this, but I have a glitch with pychilizer's Room Data Sheets. It not working regardless of template or project (tested it multiple time on Revit 2022)

To Reproduce

Go to Pychilizer > Project >
Click on Room Data Sheets.
select rooms
click finish
select as needed (some times I didn't change anything) in the pop window and click OK
get error screen
Expected behavior
I expected creation of interiors placed on sheet.

Screenshots

Desktop (please complete the following information):

OS: Windows 10
pyRevit Version 4.8.12.22247+0031
pyRevit Environment:
C:\Users\Earl>pyrevit env
==> Registered Clones (full git repos)
==> Registered Clones (deployed from archive/image)
master | Deploy: "basepublic" | Branch: "master" | Version: "4.8.12.22247+0031" | Path: "C:\Users\Earl\AppData\Roaming\pyRevit-Master"
==> Attachments
master | Product: "Autodesk Revit 2023" | Engine: IPY277 (277) | Path: "C:\Users\Earl\AppData\Roaming\pyRevit-Master"
master | Product: "Autodesk Revit 2022" | Engine: IPY277 (277) | Path: "C:\Users\Earl\AppData\Roaming\pyRevit-Master"
master | Product: "2019.2.3" | Engine: IPY277 (277) | Path: "C:\Users\Earl\AppData\Roaming\pyRevit-Master"
==> Installed Extensions
==> Default Extension Search Path
C:\Users\Earl\AppData\Roaming\pyRevit\Extensions
==> Extension Search Paths
==> Extension Sources - Default
https://github.com/eirannejad/pyRevit/raw/master/extensions/extensions.json
==> Extension Sources - Additional
==> Installed Revits
Autodesk Revit 2023 | Version: 23.0.20.21 | Build: 20220726_1500(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2023"
Autodesk Revit 2022 | Version: 22.1.30.34 | Build: 20220520_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2022"
2019.2.3 | Version: 19.2.30.41 | Build: 20210416_1515(x64) | Language: 1033 | Path: "C:\Program Files\Autodesk\Revit 2019"
==> Running Revit Instances
Error: Object reference not set to an instance of an object.
Run with "--debug" option to see debug messages
Additional context
Error:
﻿
ERROR [pyrevit.revit.db.transaction] Error in Transaction Context. Rolling back changes. | <type 'exceptions.Exception'>:An internal error has occurred.
IronPython Traceback:
Traceback (most recent call last):
File "C:\Users\Earl\AppData\Roaming\pyRevit\Extensions\pyChilizer.extension\pyChilizer.tab\Project.panel\rooms.stack\Room Data Sheets.pushbutton\script.py", line 284, in
File "C:\Users\Earl\AppData\Roaming\pyRevit\Extensions\pyChilizer.extension\lib\pychilizer\geo.py", line 274, in set_crop_to_bb
Exception: An internal error has occurred.

Script Executor Traceback:
Autodesk.Revit.Exceptions.InternalException: An internal error has occurred.
at Microsoft.Scripting.Interpreter.ThrowInstruction.Run(InterpretedFrame frame)
at Microsoft.Scripting.Interpreter.Interpreter.HandleException(InterpretedFrame frame, Exception exception)
at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
at PyRevitLabs.PyRevit.Runtime.IronPythonEngine.Execute(ScriptRuntime& runtime)

**Comment by dariaivanciucova** [comment]
solved
