### ISSUE TITLE
Colorize View by Type / Colorize 3D by Type

### ISSUE THREAD

**Issue by heinrichboldt** [dnenov/pyChilizer#26]
I love this Idea

but I am missing the category "OST_SpecialityEquipment"
and 
would like to get the Project Lines colored same as the Surface Pattern

thank you!

**Comment by rastermadre** [comment]
@heinrichboldt thanks for the feedback, we'll include more override options for the next update

**Comment by rastermadre** [comment]
@heinrichboldt added more override options with shift-click and added the Speciality Equipment category.

**Comment by jmcouffin** [comment]
@rastermadre why not a category list selector in general -> no config needed then

**Comment by rastermadre** [comment]
@jmcouffin do you mean like the one for 'Pick'? the config is currently for choosing the overrides method (Projectio/Cut/Surface/Line)

**Comment by jmcouffin** [comment]
I mean for picking the category itself, having a select from list would do @dariaivanciucova

**Comment by dariaivanciucova** [comment]
@jmcouffin my worry is that including all the possible categories can make the tool less usable. But I agree that in some special cases, it can be very useful to isolate something very niche. I personally often use the tool just to isolate a category. 

i think the best solution would be the short, everyday list with 10 basic categories 
![image](https://user-images.githubusercontent.com/43077096/236181251-2249597e-532e-4f99-a93d-3d035d535db4.png)

+ Shift-click settings with the full list of possible cats together with overrides 
![image](https://user-images.githubusercontent.com/43077096/236182325-d83e6207-0856-41c5-a39d-af0b1d0a0ac3.png)


But for that i'll need more time and to up my wpf skills :)

**Comment by jmcouffin** [comment]
@dariaivanciucova agreed
no need for more wpf skills IMHO
Just use the pyrevit forms module an d the selectfromlist() will do the trick for all that in a two steps process.
First you get to pick the categories you want, then specify the overrides you want. 
#my2cents
