### ISSUE TITLE
Add Doors support in "Filter by value"

### ISSUE THREAD

**Issue by dsellam** [dnenov/pyChilizer#49]
Is it possible to add some categories to this awesome tool ?
Doors for example ?

**Comment by jmcouffin** [comment]
You may want to check if your version of pychilizer is up to date. 
The tool has this feature that lets you add any category.
You can configure the tool using the shift+click button and then run the tool

**Comment by dsellam** [comment]
Thank you Jean-Marc, I saw the Settings but didn't notice sooner that ticking all the checkboxes change the category selector and helps to see all the categories , including doors.
