### ISSUE TITLE
Conflict between "filter by value" and View Template

### ISSUE THREAD

**Issue by dsellam** [dnenov/pyChilizer#50]
We cannot understand how it may work for adding filters to a view with view template ? Is it possible to add some explanation in the tooltip ? or resolve conflicts between view filters and view template filters ?

**Comment by dariaivanciucova** [comment]
Hi @dsellam, 

we'll add an explanation to the tooltip, good idea. 
this tool will not override your view template settings. if you want to add the filters to your view template, you'll have to disable the view template, run the script and then create a new view template from the view settings. your new view template will include both previous settings + new filters.

**Comment by dsellam** [comment]
Thank you ! I don't want to open a new issue for that but maybe a tooltip can be useful for "Legends from filters" also. thank you for this awesome tools more globally they are really nice to use
